# Programmers _ Lv3 _ 없어진 기록 찾기

SELECT O.ANIMAL_ID, O.NAME -- OUTS를 LEFT에 두고 LEFT JOIN 하였으므로
FROM ANIMAL_OUTS O LEFT JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID -- ANIMAL_ID를 key로 JOIN
WHERE I.ANIMAL_ID IS NULL -- 보호소에 들어온 기록이 없음
ORDER BY I.ANIMAL_ID ASC;