# Programmers _ Lv3

SELECT INS.NAME, INS.DATETIME
FROM ANIMAL_INS INS LEFT JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
-- INS 와 OUT를 조인한 후
WHERE OUTS.DATETIME IS NULL -- 아직 입양을 못 간 동물 중
ORDER BY INS.DATETIME ASC -- 보호소에 들어온 순서대로 정렬
LIMIT 3; -- 3마리 제한